name: Hexo Deploy

# master branch on push, auto run
on:
  push:
    branches:
      - master

jobs:
  Deploy-Pages:
    name: Deploy Hexo Public To Pages
      #runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@v2

    # from: https://github.com/actions/setup-node
    - name: Setup Node.js v8.17.0
      uses: actions/setup-node@v2
      with:
        node-version: "8.17.0"

    - name: Setup Git Infomation
      run: |
        git config --global user.name 'tangleithu'
        git config --global user.email 'githubworkflow@tanglei.name'

    - name: Get Latest Commit Message
      run: |
        git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log

    - name: Setup Hexo Dependencies
      run: |
        node -v && npm --version
        npm install hexo-cli@3.1.0 -g
        npm install
        hexo --version
        git diff | cat

    - name: Generate public files
      run: |
        hexo clean
        hexo generate --debug

    - name: Deploy To Github Pages
      env:
        Github_Pages: github.com/tl3shi/hexo.tanglei.name
        Github_Token: ${{ secrets.TOKEN_GITHUBAPI }}
      run: |
        du -h -d 1
        mv public .deploy && cd .deploy
        cp -R ./resources deploy/ && cp -R ./wp-content .deploy/
        git init && git add .
        git commit -F ../commit-message.log
        git push --force "https://${Github_Token}@${Github_Pages}" master:gh-pages-test
